Algoritmo "semnome"
// Crie um programa que declare 3 variáveis para receber o Nome, o peso e a altura de uma pessoa. Ao final imprima os dados na tela.

Var
 nome : caractere;
 peso, altura : real;

Inicio
      escreva("Digite seu nome: ")
      leia(nome)
      escreva("Digite seu peso: ")
      leia(peso)
      escreva("Digite sua altura: ")
      leia(altura)
      
      escreva("Nome: ", nome, " Altura: ", altura, " Peso: ", peso)

Fimalgoritmo